applications/urls.py
from django.urls import path

from applications.views.parties import consignees, end_users, third_parties, ultimate_end_users
from applications.views import (
    goods,
    documents,
    locations,
    additional_documents,
    common,
    edit,
    told_by_an_official,
    optional_note,
    goods_types,
    f680_details,
    clearance,
    questions,
    end_use_details,
)

app_name = "applications"
urlpatterns = [
    # Common
    path("", common.ApplicationsList.as_view(), name="applications"),
    path("<uuid:pk>/delete/", common.DeleteApplication.as_view(), name="delete"),
    path("<uuid:pk>/task-list/", common.ApplicationTaskList.as_view(), name="task_list"),
    path("<uuid:pk>/submit-success/", common.ApplicationSubmitSuccessPage.as_view(), name="success_page"),
    path("<uuid:pk>/edit-type/", common.ApplicationEditType.as_view(), name="edit_type"),
    path("<uuid:pk>/check-your-answers/", common.CheckYourAnswers.as_view(), name="check_your_answers"),
    path("<uuid:pk>/submit/", common.Submit.as_view(), name="submit"),
    path("<uuid:pk>/copy/", common.ApplicationCopy.as_view(), name="copy"),
    path("<uuid:pk>/ecju-queries/<uuid:query_pk>/", common.RespondToQuery.as_view(), name="respond_to_query"),
    # Standard and Open Licence
    path("<uuid:pk>/edit/reference-name/", edit.EditReferenceName.as_view(), name="edit_reference_name",),
    path("<uuid:pk>/edit/goods-categories/", edit.EditGoodsCategories.as_view(), name="edit_goods_categories",),
    path(
        "<uuid:pk>/edit/told-by-an-official/",
        told_by_an_official.ApplicationEditToldByAnOfficial.as_view(),
        name="edit_told_by_an_official",
    ),
    # HMRC Query
    path("<uuid:pk>/optional-note/", optional_note.ApplicationOptionalNote.as_view(), name="optional_note"),
    # Goods
    path("<uuid:pk>/goods/", goods.DraftGoodsList.as_view(), name="goods"),
    path("<uuid:pk>/goods/add-new/", goods.AddGood.as_view(), name="new_good"),
    path(
        "<uuid:pk>/goods/add-new/<uuid:good_pk>/add-document/",
        goods.CheckDocumentGrading.as_view(),
        name="add_document",
    ),
    path("<uuid:pk>/goods/add-new/<uuid:good_pk>/attach/", goods.AttachDocument.as_view(), name="attach_documents"),
    path("<uuid:pk>/goods/add-preexisting/", goods.GoodsList.as_view(), name="preexisting_good"),
    path("<uuid:pk>/goods/<uuid:good_pk>/add/", goods.AddGoodToApplication.as_view(), name="add_good_to_application",),
    path(
        "<uuid:pk>/good-on-application/<uuid:good_on_application_pk>/remove/",
        goods.RemovePreexistingGood.as_view(),
        name="remove_preexisting_good",
    ),
    # F680 details
    path("<uuid:pk>/f680-details/", f680_details.F680Details.as_view(), name="f680_details"),
    path("<uuid:pk>/questions/", questions.AdditionalInformationFormView.as_view(), name="questions"),
    # Goods Types
    path("<uuid:pk>/goods-types/", goods_types.GoodsTypeList.as_view(), name="goods_types"),
    path("<uuid:pk>/goods-types/countries/", goods_types.GoodsTypeCountries.as_view(), name="goods_countries"),
    path("<uuid:pk>/goods-types/add/", goods_types.GoodsTypeAdd.as_view(), name="add_goods_type"),
    path(
        "<uuid:pk>/goods-types/remove/<uuid:goods_type_pk>/",
        goods_types.GoodsTypeRemove.as_view(),
        name="remove_goods_type",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/attach",
        documents.AttachDocuments.as_view(),
        name="goods_type_attach_document",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="goods_type_download_document",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="goods_type_delete_document",
    ),
    # Goods locations
    path("<uuid:pk>/goods-locations/", locations.GoodsLocation.as_view(), name="location"),
    path("<uuid:pk>/goods-locations/edit/", locations.EditGoodsLocation.as_view(), name="edit_location"),
    path("<uuid:pk>/goods-locations/existing-sites/", locations.ExistingSites.as_view(), name="existing_sites"),
    path(
        "<uuid:pk>/goods-locations/external-locations/select/",
        locations.SelectAddExternalLocation.as_view(),
        name="select_add_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/add/",
        locations.AddExternalLocation.as_view(),
        name="add_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/<uuid:ext_loc_pk>/",
        locations.RemoveExternalLocation.as_view(),
        name="remove_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/preexisting/",
        locations.AddExistingExternalLocation.as_view(),
        name="add_preexisting_external_location",
    ),
    path("<uuid:pk>/goods-locations/countries/", locations.Countries.as_view(), name="countries"),
    # End User
    path("<uuid:pk>/end-user/", end_users.EndUser.as_view(), name="end_user"),
    path("<uuid:pk>/end-user/add/", end_users.AddEndUser.as_view(), name="add_end_user"),
    path("<uuid:pk>/end-user/set/", end_users.SetEndUser.as_view(), name="set_end_user"),
    path("<uuid:pk>/end-user/copy/", end_users.CopyEndUsers.as_view(), name="end_users_copy"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/", end_users.EndUser.as_view(), name="end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/edit/", end_users.EditEndUser.as_view(), name="edit_end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/copy/", end_users.CopyEndUser.as_view(), name="copy_end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/remove/", end_users.RemoveEndUser.as_view(), name="remove_end_user"),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/attach/",
        documents.AttachDocuments.as_view(),
        name="end_user_attach_document",
    ),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="end_user_download_document",
    ),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="end_user_delete_document",
    ),
    # Consignee
    path("<uuid:pk>/consignee/", consignees.Consignee.as_view(), name="consignee"),
    path("<uuid:pk>/consignee/add/", consignees.AddConsignee.as_view(), name="add_consignee"),
    path("<uuid:pk>/consignee/set/", consignees.SetConsignee.as_view(), name="set_consignee"),
    path("<uuid:pk>/consignee/copy/", consignees.CopyConsignees.as_view(), name="consignees_copy"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/", consignees.Consignee.as_view(), name="consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/edit/", consignees.EditConsignee.as_view(), name="edit_consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/copy/", consignees.CopyConsignee.as_view(), name="copy_consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/remove/", consignees.RemoveConsignee.as_view(), name="remove_consignee"),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/attach/",
        documents.AttachDocuments.as_view(),
        name="consignee_attach_document",
    ),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="consignee_download_document",
    ),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="consignee_delete_document",
    ),
    # End use details
    path("<uuid:pk>/end-use-details/", end_use_details.EndUseDetails.as_view(), name="end_use_details"),
    # Ultimate end users
    path("<uuid:pk>/ultimate-end-users/", ultimate_end_users.UltimateEndUsers.as_view(), name="ultimate_end_users"),
    path(
        "<uuid:pk>/ultimate-end-users/add/",
        ultimate_end_users.AddUltimateEndUser.as_view(),
        name="add_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/set/",
        ultimate_end_users.SetUltimateEndUser.as_view(),
        name="set_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/copy/",
        ultimate_end_users.CopyUltimateEndUsers.as_view(),
        name="ultimate_end_users_copy",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/copy/",
        ultimate_end_users.CopyUltimateEndUser.as_view(),
        name="copy_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/remove/",
        ultimate_end_users.RemoveUltimateEndUser.as_view(),
        name="remove_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/",
        ultimate_end_users.UltimateEndUsers.as_view(),
        name="ultimate_end_users",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/attach",
        documents.AttachDocuments.as_view(),
        name="ultimate_end_user_attach_document",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="ultimate_end_user_download_document",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="ultimate_end_user_delete_document",
    ),
    # Third parties
    path("<uuid:pk>/third-parties/", third_parties.ThirdParties.as_view(), name="third_parties"),
    path("<uuid:pk>/third-parties/add/", third_parties.AddThirdParty.as_view(), name="add_third_party"),
    path("<uuid:pk>/third-parties/set/", third_parties.SetThirdParty.as_view(), name="set_third_party"),
    path("<uuid:pk>/third-parties/copy/", third_parties.CopyThirdParties.as_view(), name="third_parties_copy"),
    path("<uuid:pk>/third-parties/<uuid:obj_pk>/", third_parties.ThirdParties.as_view(), name="third_parties"),
    path(

conf/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("applications/", include("applications.urls")),
    path("apply-for-a-licence/", include("apply_for_a_licence.urls")),
    path("auth/", include("auth.urls")),
    path("end-users/", include("end_users.urls")),
    path("goods/", include("goods.urls")),
    path("licences/", include("licences.urls")),
    path("organisation/", include("organisation.urls")),
    path("", include("hmrc.urls")),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("pick-organisation/", views.PickOrganisation.as_view(), name="pick_organisation"),
    path(
        "register-an-organisation/",
        views.RegisterAnOrganisationTriage.as_view(),
        name="register_an_organisation_triage",
    ),
    path(
        "register-an-organisation/confirm/",
        views.RegisterAnOrganisationConfirmation.as_view(),
        name="register_an_organisation_confirm",
    ),
    path(
        "register-an-organisation/<str:type>/<str:location>/",
        views.RegisterAnOrganisation.as_view(),
        name="register_an_organisation",
    ),
]

hmrc/urls.py
from django.urls import path

from hmrc import views

app_name = "hmrc"

urlpatterns = [
    path("raise-a-query/", views.SelectAnOrganisation.as_view(), name="raise_a_query"),
    path("<uuid:org_id>/reference-name/", views.ReferenceName.as_view(), name="reference_name"),
]

hub/urls.py
from django.urls import path

from . import views

app_name = 'hub'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
]

applications/forms/hmrc.py
from django.urls import reverse_lazy

from lite_content.lite_exporter_frontend import strings
from applications.components import back_to_task_list
from core.helpers import str_date_only
from lite_forms.components import Form, TextArea, TextInput, Summary, HiddenField


def confirm_organisation_form(organisation):
    return Form(
        title=strings.Hmrc.ConfirmOrg.TITLE,
        questions=[
            Summary(
                values={
                    "Name": organisation["name"],
                    "Registration number": organisation["registration_number"],
                    "EORI number": organisation["eori_number"],
                    "VAT number": organisation["vat_number"],
                    "Joined on": str_date_only(organisation["created_at"]),
                }
            ),
            HiddenField("organisation", organisation["id"]),
        ],
        default_button_name=strings.Hmrc.ConfirmOrg.BUTTON_TEXT,
    )


def query_explanation_form(application_id):
    return Form(
        title=strings.Hmrc.QueryExplanation.TITLE,
        questions=[TextArea(name="reasoning", optional=True, extras={"max_length": 1000,})],
        default_button_name=strings.Hmrc.QueryExplanation.BUTTON_TEXT,
        back_link=back_to_task_list(application_id),
    )


def reference_name_form():
    return Form(
        title="Enter a reference for this HMRC Query",
        description="Give the query a reference name so you can refer back to it when needed.",
        questions=[TextInput(name="name"),],
        default_button_name="Continue",
    )

hmrc/views.py
from http import HTTPStatus

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from applications.forms.hmrc import confirm_organisation_form, reference_name_form
from applications.services import post_applications
from conf.constants import CaseTypes
from core.helpers import convert_dict_to_query_params
from core.permissions import validate_is_in_organisation_type
from core.services import get_organisations, get_organisation
from lite_forms.generators import form_page
from lite_forms.views import SingleFormView


class SelectAnOrganisation(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        validate_is_in_organisation_type(request, "hmrc")
        return super(SelectAnOrganisation, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        search_term = request.GET.get("search_term", "").strip()
        params = {"page": int(request.GET.get("page", 1))}

        if search_term:
            params["search_term"] = search_term

        organisations = get_organisations(request, org_type=["commercial", "individual"], **params)
        params_str = convert_dict_to_query_params(params)

        context = {
            "organisations": organisations,
            "params": params,
            "page": params.pop("page"),
            "params_str": params_str,
            "show_error": kwargs.get("show_error", False),
        }
        return render(request, "hmrc/select-organisation.html", context)

    def post(self, request, *args, **kwargs):
        action = request.POST.get("action")
        organisation = request.POST.get("organisation")

        if action == "continue":
            if organisation:
                organisation = get_organisation(request, request.POST.get("organisation"))
                return form_page(request, confirm_organisation_form(organisation))
            else:
                # Return an error if the user hasn't selected an organisation
                return self.get(request, show_error=True, *args, **kwargs)
        else:
            return redirect(reverse_lazy("hmrc:reference_name", kwargs={"org_id": organisation}))


class ReferenceName(TemplateView):
    def get(self, request, org_id):
        return form_page(request, reference_name_form())

    def post(self, request, org_id):
        data = {"name": request.POST["name"], "application_type": CaseTypes.CRE, "organisation": str(org_id)}
        response, status_code = post_applications(request, data)
        if status_code != HTTPStatus.CREATED:
            return form_page(request, reference_name_form(), errors=response.get("errors"))
        else:
            return redirect(reverse_lazy("applications:task_list", kwargs={"pk": response["id"]}))

templates/hmrc/select-organisation.html
{% extends 'layouts/two-pane.html' %}

{% load svg %}

{% block back_link %}
	<a href="{% url 'core:home' %}" id="back-link" class="govuk-back-link">Back to dashboard</a>
{% endblock %}

{% block two_thirds %}
	{% if show_error %}
		<div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary">
			<h2 class="govuk-error-summary__title" id="error-summary-title">
				There is a problem
			</h2>
			<div class="govuk-error-summary__body">
				<ul class="govuk-list govuk-error-summary__list">
					<li>
						<a href="#">Select an organisation</a>
					</li>
				</ul>
			</div>
		</div>
	{% endif %}

	<legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
		<h1 class="govuk-fieldset__heading">
			{% block title %}Search for an organisation or individual{% endblock %}
		</h1>
	</legend>
	<span class="govuk-hint">
		Enter the name or company registration number.
	</span>
	<form method="get" class="govuk-!-margin-bottom-6">
		<div class="lite-search__container">
			<input type="search" name="search_term" class="govuk-input" name="search" id="search" value="{{ params.search_term }}" placeholder="Search organisations" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
			<button class="lite-search__button" type="submit">
				{% svg 'search' %}
				<span>Search</span>
			</button>
		</div>
	</form>

	{% if organisations.results|length and params.search_term %}
		<form method="post">
			{% csrf_token %}
			<div class="govuk-form-group {% if show_error %}govuk-form-group--error{% endif %}">
				{% if show_error %}
					<span id="passport-issued-error" class="govuk-error-message">
						<span class="govuk-visually-hidden">Error:</span> Select an organisation
					</span>
				{% endif %}
				<div class="govuk-radios">
					{% for organisation in organisations.results %}
						<div class="govuk-radios__item">
							<input class="govuk-radios__input" id="organisation-{{ organisation.id }}" name="organisation" type="radio" value="{{ organisation.id }}">
							<label class="govuk-label govuk-radios__label" for="organisation-{{ organisation.id }}">
								{{ organisation.name|highlight_text:params.search_term }}
							</label>
							<span id="sign-in-item-hint" class="govuk-hint govuk-radios__hint">
								{{ organisation.registration_number|highlight_text:params.search_term }}<br>
								{{ organisation.type.value }}
							</span>
						</div>
					{% endfor %}
				</div>
			</div>

			{% include "includes/pagination.html" with data=data %}

			<button class="govuk-button" name="action" value="continue" data-module="govuk-button">
				Continue
			</button>
		</form>
	{% elif params.search_term %}
		<div class="lite-information-text">
			<span class="lite-information-text__icon" aria-hidden="true">!</span>
			<p class="lite-information-text__text">
				<span class="govuk-visually-hidden">Information</span>
				There are no organisations to show.<br>
				<a class="govuk-link govuk-link--no-visited-state" href="{{ INTERNAL_URL }}/organisations/register/">
					Register the organisation or individual
				</a>
			</p>
		</div>
	{% endif %}
{% endblock %}

templates/hmrc/task-list.html
{% extends 'layouts/two-pane.html' %}

{% block back_link %}{% endblock %}

{% block two_thirds %}
	<h1 class="govuk-heading-xl govuk-!-margin-bottom-9">
		{% block title %}
			Raise a query on behalf of {{ application.organisation.name }}
		{% endblock %}
	</h1>

	<ol class="lite-task-list">
		<li>
			<h2 class="lite-task-list__section">
				<span class="lite-task-list__section-number">1. </span> Provide details of your query
			</h2>
			<ul class="lite-task-list__items">
				{% url 'applications:goods_types' application.id as goods_url %}
				{% include "includes/task-list-item.html" with id="goods" title="Products" url=goods_url status=goods_types_status %}

				{% url 'applications:location' application.id as goods_location_url %}
				{% include "includes/task-list-item.html" with id="goods-location" title="Location" url=goods_location_url status=goods_locations_status %}

				{% url 'applications:end_user' application.id as end_user_url %}
				{% include "includes/task-list-item.html" with id="end-user" title="End user" url=end_user_url status=end_user_status %}

				{% url 'applications:ultimate_end_users' application.id as ultimate_end_user_url %}
				{% include "includes/task-list-item.html" with title="Ultimate recipient" url=ultimate_end_user_url status=ultimate_end_users_status optional=True %}

				{% url 'applications:third_parties' application.id as third_parties_url %}
				{% include "includes/task-list-item.html" with title="Third parties" url=third_parties_url status=third_parties_status optional=True %}

				{% url 'applications:consignee' application.id as consignee_url %}
				{% include "includes/task-list-item.html" with title="Consignee" url=consignee_url status=consignee_status optional=True %}

				{% url 'applications:additional_documents' application.id as supporting_documentation_url %}
				{% include "includes/task-list-item.html" with title="Supporting documents" url=supporting_documentation_url status=supporting_documentation_status optional=True %}

				{% url 'applications:optional_note' application.id as optional_note_url %}
				{% include "includes/task-list-item.html" with id="reasoning" title="Reason for query" url=optional_note_url status=optional_note_status optional=True %}
			</ul>
		</li>
	</ol>

	<ol class="lite-task-list">
		<li>
			<h2 class="lite-task-list__section">
				<span class="lite-task-list__section-number">2. </span> Check your answers
			</h2>
			<ul class="lite-task-list__items">
				{% if show_submit_button %}
					{% url 'applications:check_your_answers' application.id as check_your_answers_url %}
					{% include "includes/task-list-item.html" with title="Check your answers" url=check_your_answers_url hide_tag=True %}
				{% else %}
					<li class="lite-task-list__item">
						<div class="lite-task-list__item-header">
							Check your answers
						</div>
					</li>
				{% endif %}
			</ul>
		</li>
		{% if show_submit_button %}
			<li>
				<form method="post">
					{% csrf_token %}
					<button type="submit" value="submit" class="govuk-button">Submit</button>
				</form>
			</li>
		{% endif %}
	</ol>

	<!-- <ol class="lite-task-list">
		<li>
			<h2 class="lite-task-list__section">
				<span class="lite-task-list__section-number">3. </span> Confirm and submit your query
			</h2>
			<ul class="lite-task-list__items">
				{% url 'applications:submit' application.id as confirm_url %}
				{% include "includes/task-list-item.html" with title="Confirm and submit your query" url=confirm_url %}
			</ul>
		</li>
	</ol> -->
{% endblock %}