conf/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("applications/", include("applications.urls")),
    path("apply-for-a-licence/", include("apply_for_a_licence.urls")),
    path("auth/", include("auth.urls")),
    path("end-users/", include("end_users.urls")),
    path("goods/", include("goods.urls")),
    path("licences/", include("licences.urls")),
    path("organisation/", include("organisation.urls")),
    path("", include("hmrc.urls")),
]

end_users/urls.py
from django.urls import path

from end_users import views

app_name = "end_users"

urlpatterns = [
    # ex: /end-users/
    path("", views.EndUsersList.as_view(), name="end_users"),
    # ex: /end-users/1234567890/
    path("<uuid:pk>/", views.EndUserDetailEmpty.as_view(), name="end_user"),
    # ex: /end-users/1234567890/copy-advisory/
    path("<uuid:pk>/copy-advisory/", views.CopyAdvisory.as_view(), name="copy"),
    # ex: /end-users/apply-for-an-advisory/
    path("apply-for-an-advisory/", views.ApplyForAnAdvisory.as_view(), name="apply"),
    # ex: /end-users/1234567890/<str:type>/
    path("<uuid:pk>/<str:type>/", views.EndUserDetail.as_view(), name="end_user_detail"),
    # ex: /end-users/1234567890/ecju-queries/43a88949-5db9-4334-b0cc-044e91827451
    path("<uuid:pk>/ecju-queries/<uuid:query_pk>/", views.RespondToQuery.as_view(), name="respond_to_query"),
]

hub/urls.py
from django.urls import path

from . import views

app_name = 'hub'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
]

applications/forms/end_user.py
from lite_content.lite_exporter_frontend import strings
from django.urls import reverse_lazy

from applications.components import back_to_task_list
from core.services import get_countries
from lite_forms.common import country_question
from lite_forms.components import RadioButtons, Form, Option, TextArea, TextInput, FormGroup, FileUpload, Label
from lite_forms.generators import confirm_form
from lite_content.lite_exporter_frontend.applications import PartyForm


def _party_type_form(application, title, button):
    return Form(
        title=title,
        questions=[
            RadioButtons(
                "sub_type",
                options=[
                    Option("government", PartyForm.Options.GOVERNMENT),
                    Option("commercial", PartyForm.Options.COMMERCIAL),
                    Option("individual", PartyForm.Options.INDIVIDUAL),
                    Option("other", PartyForm.Options.OTHER, show_or=True),
                ],
            ),
        ],
        default_button_name=button,
        back_link=back_to_task_list(application["id"]),
    )


def _party_name_form(title, button):
    return Form(title=title, questions=[TextInput("name"),], default_button_name=button)


def _party_website_form(title, button):
    return Form(title=title, questions=[TextInput("website", optional=True),], default_button_name=button,)


def _party_address_form(title, button):
    return Form(
        title=title,
        questions=[TextArea("address", "Address"), country_question(countries=get_countries(None, True), prefix=""),],
        default_button_name=button,
    )


def new_party_form_group(application, strings):
    return FormGroup(
        [
            _party_type_form(application, strings.TITLE, strings.BUTTON),
            _party_name_form(strings.NAME_FORM_TITLE, strings.BUTTON),
            _party_website_form(strings.WEBSITE_FORM_TITLE, strings.BUTTON),
            _party_address_form(strings.ADDRESS_FORM_TITLE, strings.SUBMIT_BUTTON),
        ]
    )


def attach_document_form(application_id, title, return_later_text, description_text=None):
    inputs = [FileUpload("documents")]
    if description_text:
        inputs.append(TextArea(title=description_text, optional=True, name="description", extras={"max_length": 280,}))
    return Form(
        title,
        strings.EndUser.Documents.AttachDocuments.DESCRIPTION,
        inputs,
        back_link=back_to_task_list(application_id),
        footer_label=Label(
            'Or <a href="'
            + str(reverse_lazy("applications:task_list", kwargs={"pk": application_id}))
            + '" class="govuk-link govuk-link--no-visited-state">'
            + return_later_text
            + "</a> "
            + strings.EndUser.Documents.ATTACH_LATER
        ),
    )


def delete_document_confirmation_form(overview_url, back_link_text):
    return confirm_form(
        title="Are you sure you want to delete this document?",
        confirmation_name="delete_document_confirmation",
        back_link_text=back_link_text,
        back_url=overview_url,
    )

end_users/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from lite_content.lite_exporter_frontend import strings
from lite_forms.components import HiddenField
from lite_forms.generators import form_page, error_page
from lite_forms.submitters import submit_paged_form

from applications.services import (
    get_case_notes,
    get_application_ecju_queries,
    post_case_notes,
    get_ecju_query,
    put_ecju_query,
    get_case_generated_documents,
)
from end_users.forms import (
    apply_for_an_end_user_advisory_form,
    copy_end_user_advisory_form,
    end_user_advisory_success_page,
    respond_to_query_form,
    ecju_query_respond_confirmation_form,
)
from end_users.services import get_end_user_advisories, post_end_user_advisories, get_end_user_advisory


class EndUsersList(TemplateView):
    def get(self, request, **kwargs):
        end_users = get_end_user_advisories(request)

        context = {
            "end_users": end_users,
        }
        return render(request, "end-users/end-users.html", context)


class CopyAdvisory(TemplateView):

    forms = None
    data = None

    def dispatch(self, request, *args, **kwargs):
        query, _ = get_end_user_advisory(request, str(kwargs["pk"]))

        self.data = {
            "end_user.name": query["end_user"]["name"],
            "end_user.website": query["end_user"]["website"],
            "end_user.address": query["end_user"]["address"],
            "end_user.country": query["end_user"]["country"]["id"],
            "end_user.type": query["end_user"]["type"],
            "reasoning": query.get("reasoning", ""),
            "note": query.get("note", ""),
            "copy_of": query["id"],
            "contact_email": query["contact_email"],
            "contact_telephone": query["contact_telephone"],
        }

        individual, commercial = False, False

        sub_type = query["end_user"]["sub_type"]["key"]
        if sub_type != "individual":
            self.data["contact_name"] = query["contact_name"]
            self.data["contact_job_title"] = query["contact_job_title"]
        else:
            individual = True

        if sub_type == "commercial":
            commercial = True
            self.data["nature_of_business"] = query["nature_of_business"]

        self.forms = copy_end_user_advisory_form(individual, commercial)

        # Add the existing end user type as a hidden field to preserve its data
        self.forms.forms[0].questions.append(HiddenField("end_user.sub_type", query["end_user"]["sub_type"]["key"]))

        return super(CopyAdvisory, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        return form_page(request, self.forms.forms[0], data=self.data)

    def post(self, request, **kwargs):
        response, data = submit_paged_form(request, self.forms, post_end_user_advisories, inject_data=self.data)

        if response:
            return response

        return end_user_advisory_success_page(request, str(data["end_user_advisory"]["reference_code"]))


class ApplyForAnAdvisory(TemplateView):

    forms = None

    def dispatch(self, request, *args, **kwargs):
        individual = request.POST.get("end_user.sub_type") == "individual"
        commercial = request.POST.get("end_user.sub_type") == "commercial"
        self.forms = apply_for_an_end_user_advisory_form(individual, commercial)

        return super(ApplyForAnAdvisory, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        return form_page(request, self.forms.forms[0])

    def post(self, request, **kwargs):
        response, data = submit_paged_form(request, self.forms, post_end_user_advisories)
        if response:
            return response

        return end_user_advisory_success_page(request, str(data["end_user_advisory"]["reference_code"]))


class EndUserDetailEmpty(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("end_users:end_user_detail", kwargs={"pk": self.kwargs["pk"], "type": "case-notes"})


class EndUserDetail(TemplateView):
    end_user_advisory_id = None
    end_user_advisory = None
    view_type = None
    case_id = None

    def dispatch(self, request, *args, **kwargs):
        self.end_user_advisory_id = str(kwargs["pk"])
        self.end_user_advisory, self.case_id = get_end_user_advisory(request, self.end_user_advisory_id)
        self.view_type = kwargs["type"]

        if self.view_type not in ["case-notes", "ecju-queries", "ecju-generated-documents"]:
            return Http404

        return super(EndUserDetail, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        context = {
            "case_id": self.case_id,
            "end_user_advisory": self.end_user_advisory,
            "type": self.view_type,
            "error": kwargs.get("error"),
            "text": kwargs.get("text", ""),
        }

        if self.view_type == "case-notes":
            case_notes = get_case_notes(request, self.case_id)["case_notes"]
            context["notes"] = case_notes

        if self.view_type == "ecju-queries":
            context["open_queries"], context["closed_queries"] = get_application_ecju_queries(request, self.case_id)

        if self.view_type == "ecju-generated-documents":
            generated_documents, _ = get_case_generated_documents(request, self.case_id)
            context["generated_documents"] = generated_documents["results"]

        return render(request, "end-users/end-user.html", context)

    def post(self, request, **kwargs):
        if self.view_type != "case-notes":
            return Http404

        response, _ = post_case_notes(request, self.case_id, request.POST)

        if "errors" in response:
            return self.get(request, error=response["errors"]["text"][0], text=request.POST.get("text"), **kwargs)

        return redirect(
            reverse_lazy("end_users:end_user_detail", kwargs={"pk": self.end_user_advisory_id, "type": "case-notes"})
        )


class RespondToQuery(TemplateView):
    end_user_advisory_id = None
    end_user_advisory = None
    view_type = None
    case_id = None
    ecju_query_id = None
    ecju_query = None

    def dispatch(self, request, *args, **kwargs):
        self.end_user_advisory_id = str(kwargs["pk"])
        self.end_user_advisory, self.case_id = get_end_user_advisory(request, self.end_user_advisory_id)

        self.ecju_query_id = str(kwargs["query_pk"])
        self.ecju_query = get_ecju_query(request, self.case_id, self.ecju_query_id)

        # If an ecju query is already responded to, return user to end_user_advisory_page
        if self.ecju_query["response"]:
            return redirect(
                reverse_lazy(
                    "end_users:end_user_detail", kwargs={"pk": self.end_user_advisory_id, "type": "ecju-queries"}
                )
            )

        return super(RespondToQuery, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        """
        Will get a text area form for the user to respond to the ecju_query
        """
        return form_page(request, respond_to_query_form(self.end_user_advisory_id, self.ecju_query))

    def post(self, request, **kwargs):
        """
        will determine what form the user is on:
        if the user is on the input form will then will determine if data is valid, and move user to confirmation form
        else will allow the user to confirm they wish to respond and post data if accepted.
        """
        form_name = request.POST.get("form_name")

        if form_name == "respond_to_query":
            # Post the form data to API for validation only
            data = {"response": request.POST.get("response"), "validate_only": True}
            response, status_code = put_ecju_query(request, self.case_id, self.ecju_query_id, data)

            if status_code != 200:
                errors = response.get("errors")
                errors = {error: message for error, message in errors.items()}
                form = respond_to_query_form(self.end_user_advisory_id, self.ecju_query)
                data = {"response": request.POST.get("response")}
                return form_page(request, form, data=data, errors=errors)
            else:
                form = ecju_query_respond_confirmation_form(
                    reverse_lazy(
                        "end_users:respond_to_query",
                        kwargs={"pk": self.end_user_advisory_id, "query_pk": self.ecju_query_id},
                    )
                )
                form.questions.append(HiddenField("response", request.POST.get("response")))
                return form_page(request, form)
        elif form_name == "ecju_query_response_confirmation":
            if request.POST.get("confirm_response") == "yes":
                data, status_code = put_ecju_query(request, self.case_id, self.ecju_query_id, request.POST)
                if "errors" in data:
                    return form_page(
                        request,
                        respond_to_query_form(self.end_user_advisory_id, self.ecju_query),
                        data=request.POST,
                        errors=data["errors"],
                    )

                return redirect(
                    reverse_lazy(
                        "end_users:end_user_detail", kwargs={"pk": self.end_user_advisory_id, "type": "ecju-queries"}
                    )
                )

            elif request.POST.get("confirm_response") == "no":
                return form_page(
                    request, respond_to_query_form(self.end_user_advisory_id, self.ecju_query), data=request.POST
                )
            else:
                error = {"required": ["Select yes to confirm you want to send the response"]}

templates/end-users/end-user.html
{% extends 'layouts/base.html' %}

{% block back_link %}
	<a href="{% url 'end_users:end_users' %}" id="back-link" class="govuk-back-link">{% lcs 'end_users.EndUserPage.BACK_LINK' %}</a>
{% endblock %}

{% block body %}
	<div class="govuk-grid-row">
		<div class="govuk-grid-column-two-thirds">
			<div class="lite-app-bar">
				<div class="lite-app-bar__content">
					<h1 class="govuk-heading-l">
						{% block title %}
							{% lcs 'end_users.EndUserPage.TITLE' %}
						{% endblock %}
					</h1>
				</div>
			</div>

			<h3 class="govuk-heading-m">{% lcs 'end_users.EndUserPage.YOUR_QUERY' %}</h3>
			<dl class="govuk-summary-list">
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.REFERENCE' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.reference_code }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.CASE_OFFICER' %}
					</dt>
					<dd id="label-application-status" class="govuk-summary-list__value">
						{% if end_user_advisory.case_officer.first_name %}
							{{ end_user_advisory.case_officer.first_name }} {{ end_user_advisory.case_officer.last_name }}
						{% else %}
							{% lcs 'end_users.EndUserPage.NO_ASSIGNED_CASE_OFFICER' %}
						{% endif %}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.REASONING_BEHIND_QUERY' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.reasoning|default_na }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.END_USER_NOTES' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.note|default_na }}
					</dd>
				</div>
			</dl>

			<br><br>

			<h3 class="govuk-heading-m">{% lcs 'end_users.EndUserPage.END_USER_DETAILS' %}</h3>
			<dl class="govuk-summary-list">
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.NAME' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.end_user.name }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.TYPE' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.end_user.sub_type.value }}
					</dd>
				</div>
				{% if end_user_advisory.end_user.sub_type.key == 'individual' %}
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.EMAIL' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_email }}
						</dd>
					</div>
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.TELEPHONE' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_telephone }}
						</dd>
					</div>
				{% endif %}
				{% if end_user_advisory.end_user.sub_type.key == 'commercial' %}
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.NATURE_OF_BUSINESS' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.nature_of_business }}
						</dd>
					</div>
				{% endif %}
				{% if end_user_advisory.end_user.sub_type.key != 'individual' %}
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.CONTACT_NAME' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_name }}
						</dd>
					</div>
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.CONTACT_JOB_TITLE' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_job_title }}
						</dd>
					</div>
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.CONTACT_JOB_EMAIL' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_email }}
						</dd>
					</div>
					<div class="govuk-summary-list__row">
						<dt class="govuk-summary-list__key">
							{% lcs 'end_users.EndUserPage.Variables.CONTACT_TELEPHONE' %}
						</dt>
						<dd class="govuk-summary-list__value">
							{{ end_user_advisory.contact_telephone }}
						</dd>
					</div>
				{% endif %}
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.ADDRESS' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.end_user.address }}<br>{{ end_user_advisory.end_user.country.name }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs 'end_users.EndUserPage.Variables.WEBSITE' %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ end_user_advisory.end_user.website|linkify }}
					</dd>
				</div>
			</dl>

			<br><br>

			<div class="lite-tabs__container">
				<div class="lite-tabs">
					<a href="{% url 'end_users:end_user_detail' end_user_advisory.id 'case-notes' %}" class="lite-tabs__tab {% if type == 'case-notes' %}lite-tabs__tab--selected{% endif %}" id="link-case-notes">
						{% lcs 'end_users.EndUserPage.Tabs.NOTES' %}
						{% if end_user_advisory.exporter_user_notification_count.casenote %}
							<div class="lite-notification-bubble">
								{{  end_user_advisory.exporter_user_notification_count.casenote }}
							</div>
						{% endif %}
					</a>
					<a href="{% url 'end_users:end_user_detail' end_user_advisory.id 'ecju-queries' %}" class="lite-tabs__tab {% if type == 'ecju-queries' %}lite-tabs__tab--selected{% endif %}" id="link-ecju-queries">
						{% lcs 'end_users.EndUserPage.Tabs.ECJU_QUERIES' %}
						{% if  end_user_advisory.exporter_user_notification_count.ecjuquery %}
							<div class="lite-notification-bubble">
								{{ end_user_advisory.exporter_user_notification_count.ecjuquery }}
							</div>
						{% endif %}
					</a>
					<a href="{% url 'end_users:end_user_detail' end_user_advisory.id 'ecju-generated-documents' %}" class="lite-tabs__tab {% if type == 'ecju-generated-documents' %}lite-tabs__tab--selected{% endif %}" id="link-ecju-generated-documents">
						{% lcs 'goods.GoodPage.Tabs.GENERATED_DOCUMENTS' %}
						{% if  end_user_advisory.exporter_user_notification_count.generatedcasedocument %}
							<div class="lite-notification-bubble">
								{{ end_user_advisory.exporter_user_notification_count.generatedcasedocument }}
							</div>
						{% endif %}
					</a>
				</div>
			</div>
			{% if type == 'case-notes' %}
				{% url "end_users:end_user_detail" end_user_advisory.id "case-notes" as post_url %}
				{% include "includes/case-notes.html" %}
			{% elif type == 'ecju-queries'%}
				{% include "end-users/tabs/ecju-queries.html" %}
			{% elif type == 'ecju-generated-documents'%}
				{% include "core/ecju-generated-documents.html" %}
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/end-users/end-users.html
{% extends 'layouts/base.html' %}

{% block back_link %}
	{% include 'includes/breadcrumbs.html' with title='end_users.EndUsersPage.TITLE' %}
{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}
					{% lcs 'end_users.EndUsersPage.TITLE' %}
				{% endblock %}
			</h1>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'end_users:apply' %}" class="govuk-button" draggable="false" role="button" id="apply">
				{% lcs "end_users.EndUsersPage.NEW_END_USER_ADVISORY_BUTTON" %}
			</a>
		</div>
	</div>

	{% if end_users %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">{% lcs "end_users.EndUserPage.Variables.NAME" %}</th>
					<th class="govuk-table__header" scope="col">{% lcs "end_users.EndUserPage.Variables.TYPE" %}</th>
					<th class="govuk-table__header" scope="col">{% lcs "end_users.EndUserPage.Variables.ADDRESS" %}</th>
					<th class="govuk-table__header" scope="col">{% lcs "end_users.EndUserPage.Variables.WEBSITE" %}</th>
					<th class="govuk-table__header" scope="col">{% lcs "end_users.EndUserPage.Variables.REFERENCE" %}</th>
					<th class="govuk-table__header" scope="col"></th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for advisory in end_users %}
					<tr id={{ advisory.id }} class="govuk-table__row">
						<td class="govuk-table__cell">
							<a id="advisory-details-link" class="govuk-link govuk-link--no-visited-state app-icon-label" href="{% url 'end_users:end_user' pk=advisory.id %}">
								{{ advisory.end_user.name }}
								{% if advisory.exporter_user_notification_count.total %}
									<span class="lite-notification-bubble">{{ advisory.exporter_user_notification_count.total }} <span class="govuk-visually-hidden"> {% lcs "end_users.EndUsersPage.NOTIFICATIONS" %}</span></span>
								{% endif %}
							</a>
						</td>
						<td class="govuk-table__cell">
							{{ advisory.end_user.sub_type.value }}
						</td>
						<td class="govuk-table__cell">
							{{ advisory.end_user.address }}, {{ advisory.end_user.country.name }}
						</td>
						<td class="govuk-table__cell">
							{% if advisory.end_user.website %}
								<a class="govuk-link" href="{{ advisory.end_user.website }}">
									{{ advisory.end_user.website|default_na }}
								</a>
							{% else %}
								{{ advisory.end_user.website|default_na }}
							{% endif %}
						</td>
						<td class="govuk-table__cell">
							{{ advisory.reference_code }}
						</td>
						<td class="govuk-table__cell">
							<a href="{% url 'end_users:copy' advisory.id %}">Copy</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		{% include "includes/notice.html" with text="end_users.EndUsersPage.NO_CONTENT_NOTICE" %}
	{% endif %}
{% endblock %}