conf/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("applications/", include("applications.urls")),
    path("apply-for-a-licence/", include("apply_for_a_licence.urls")),
    path("auth/", include("auth.urls")),
    path("end-users/", include("end_users.urls")),
    path("goods/", include("goods.urls")),
    path("licences/", include("licences.urls")),
    path("organisation/", include("organisation.urls")),
    path("", include("hmrc.urls")),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("pick-organisation/", views.PickOrganisation.as_view(), name="pick_organisation"),
    path(
        "register-an-organisation/",
        views.RegisterAnOrganisationTriage.as_view(),
        name="register_an_organisation_triage",
    ),
    path(
        "register-an-organisation/confirm/",
        views.RegisterAnOrganisationConfirmation.as_view(),
        name="register_an_organisation_confirm",
    ),
    path(
        "register-an-organisation/<str:type>/<str:location>/",
        views.RegisterAnOrganisation.as_view(),
        name="register_an_organisation",
    ),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"
urlpatterns = [
    path("", views.Goods.as_view(), name="goods"),
    path("add/", views.AddGood.as_view(), name="add"),
    path("<uuid:pk>/edit/", views.EditGood.as_view(), name="edit"),
    path("<uuid:pk>/delete/", views.DeleteGood.as_view(), name="delete"),
    path("<uuid:pk>/add-document/", views.CheckDocumentGrading.as_view(), name="add_document"),
    path("<uuid:pk>/documents/<uuid:file_pk>/", views.Document.as_view(), name="document"),
    path("<uuid:pk>/documents/<uuid:file_pk>/delete/", views.DeleteDocument.as_view(), name="delete_document"),
    path("<uuid:pk>/attach/", views.AttachDocuments.as_view(), name="attach_documents"),
    path("<uuid:pk>/raise-good-query/", views.RaiseGoodsQuery.as_view(), name="raise_goods_query"),
    path("<uuid:pk>", views.GoodsDetailEmpty.as_view(), name="good"),
    path("<uuid:pk>/<str:type>/", views.GoodsDetail.as_view(), name="good_detail"),
    path("<uuid:pk>/ecju-queries/<uuid:query_pk>/", views.RespondToQuery.as_view(), name="respond_to_query"),
]

hub/urls.py
from django.urls import path

from . import views

app_name = 'hub'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
]

applications/forms/goods.py
from django.urls import reverse_lazy

from conf.constants import EXHIBITION
from core.services import get_units, get_item_types
from goods.helpers import good_summary
from lite_content.lite_exporter_frontend import strings
from lite_content.lite_exporter_frontend.goods import AddGoodToApplicationForm
from lite_forms.components import (
    Form,
    HiddenField,
    Select,
    QuantityInput,
    CurrencyInput,
    RadioButtons,
    Option,
    BackLink,
)


def exhibition_good_on_application_form(request, good, application_id):
    return Form(
        title=AddGoodToApplicationForm.Exhibition.TITLE,
        description=AddGoodToApplicationForm.Exhibition.DESCRIPTION,
        questions=[
            HiddenField(name="good_id", value=good.get("id")),
            RadioButtons(title="", description="", name="item_type", options=get_item_types(request)),
        ],
        back_link=BackLink(
            AddGoodToApplicationForm.Exhibition.BACK_LINK,
            reverse_lazy("applications:preexisting_good", kwargs={"pk": application_id}),
        ),
    )


def good_on_application_form(request, good, sub_case_type, application_id):
    if sub_case_type["key"] == EXHIBITION:
        return exhibition_good_on_application_form(request, good, application_id)
    else:
        return Form(
            title=AddGoodToApplicationForm.TITLE,
            description=AddGoodToApplicationForm.DESCRIPTION,
            questions=[
                good_summary(good),
                HiddenField(name="good_id", value=good.get("id")),
                Select(
                    title=AddGoodToApplicationForm.Units.TITLE,
                    description="<noscript>" + AddGoodToApplicationForm.Units.DESCRIPTION + "</noscript>",
                    name="unit",
                    options=get_units(request),
                ),
                QuantityInput(
                    title=AddGoodToApplicationForm.Quantity.TITLE,
                    description=AddGoodToApplicationForm.Quantity.DESCRIPTION,
                    name="quantity",
                ),
                CurrencyInput(
                    title=AddGoodToApplicationForm.VALUE.TITLE,
                    description=AddGoodToApplicationForm.VALUE.DESCRIPTION,
                    name="value",
                ),
                RadioButtons(
                    name="is_good_incorporated",
                    title=AddGoodToApplicationForm.Incorporated.TITLE,
                    description=AddGoodToApplicationForm.Incorporated.DESCRIPTION,
                    options=[
                        Option(True, AddGoodToApplicationForm.Incorporated.YES),
                        Option(False, AddGoodToApplicationForm.Incorporated.NO),
                    ],
                    classes=["govuk-radios--inline"],
                ),
            ],
            back_link=BackLink(
                strings.BACK_TO_APPLICATION,
                reverse_lazy("applications:preexisting_good", kwargs={"pk": application_id}),
            ),
            javascript_imports=["/assets/javascripts/add_good.js"],
        )

applications/views/goods.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from s3chunkuploader.file_handler import S3FileUploadHandler

from applications.forms.goods import good_on_application_form
from applications.helpers.check_your_answers import get_total_goods_value
from applications.services import (
    get_application,
    get_application_goods,
    get_application_goods_types,
    post_good_on_application,
    delete_application_preexisting_good,
    add_document_data,
)
from conf.constants import EXHIBITION
from core.helpers import convert_dict_to_query_params

from goods.forms import document_grading_form, attach_documents_form, add_good_form_group
from goods.services import (
    get_goods,
    get_good,
    post_goods,
    post_good_documents,
    post_good_document_sensitivity,
    validate_good,
    post_good_with_pv_grading,
)
from lite_content.lite_exporter_frontend import strings
from lite_forms.generators import error_page, form_page
from lite_forms.views import SingleFormView, MultiFormView


class DraftGoodsList(TemplateView):
    def get(self, request, **kwargs):
        """
        List all goods relating to the draft
        """
        draft_id = str(kwargs["pk"])
        application = get_application(request, draft_id)
        goods = get_application_goods(request, draft_id)
        exhibition = application["case_type"]["sub_type"]["key"] == EXHIBITION

        context = {"goods": goods, "application": application, "exhibition": exhibition}
        if not exhibition:
            context["goods_value"] = get_total_goods_value(goods)
        return render(request, "applications/goods/index.html", context)


class GoodsList(TemplateView):
    def get(self, request, **kwargs):
        """
        List of existing goods  (add-preexisting)
        """
        application_id = str(kwargs["pk"])
        application = get_application(request, application_id)
        description = request.GET.get("description", "").strip()
        part_number = request.GET.get("part_number", "").strip()
        control_rating = request.GET.get("control_rating", "").strip()

        params = {
            "page": int(request.GET.get("page", 1)),
            "description": description,
            "part_number": part_number,
            "control_rating": control_rating,
            "for_application": "True",
        }
        goods_list = get_goods(request, **params)

        context = {
            "application": application,
            "data": goods_list,
            "description": description,
            "part_number": part_number,
            "control_code": control_rating,
            "draft_id": application_id,
            "params": params,
            "page": params.pop("page"),
            "params_str": convert_dict_to_query_params(params),
        }
        return render(request, "applications/goods/preexisting.html", context)


class AddGood(MultiFormView):
    actions = [validate_good, post_goods, post_good_with_pv_grading]

    def init(self, request, **kwargs):
        self.draft_pk = str(kwargs["pk"])
        self.forms = add_good_form_group(draft_pk=self.draft_pk)
        self.action = post_goods

    def on_submission(self, request, **kwargs):
        self.draft_pk = str(kwargs["pk"])
        is_pv_graded = request.POST.copy().get("is_pv_graded", "").lower() == "yes"
        self.forms = add_good_form_group(is_pv_graded, draft_pk=self.draft_pk)
        if int(self.request.POST.get("form_pk")) == 1:
            self.action = self.actions[2]
        elif (int(self.request.POST.get("form_pk")) == 0) and is_pv_graded:
            self.action = self.actions[0]

    def get_success_url(self):
        return reverse_lazy(
            "applications:add_document",
            kwargs={"pk": self.draft_pk, "good_pk": self.get_validated_data()["good"]["id"]},
        )


class CheckDocumentGrading(SingleFormView):
    def init(self, request, **kwargs):
        self.draft_pk = kwargs["pk"]
        self.object_pk = kwargs["good_pk"]
        self.form = document_grading_form(request, self.object_pk)
        self.action = post_good_document_sensitivity

    def get_success_url(self):
        good = self.get_validated_data()["good"]
        if good["missing_document_reason"]:
            url = "applications:add_good_to_application"
        else:
            url = "applications:attach_documents"
        return reverse_lazy(url, kwargs={"pk": self.draft_pk, "good_pk": self.object_pk})


@method_decorator(csrf_exempt, "dispatch")
class AttachDocument(TemplateView):
    def get(self, request, **kwargs):
        good_id = str(kwargs["good_pk"])
        draft_id = str(kwargs["pk"])
        back_link = reverse_lazy("applications:add_good_to_application", kwargs={"pk": draft_id, "good_pk": good_id})
        form = attach_documents_form(back_link)
        return form_page(request, form, extra_data={"good_id": good_id})

    def post(self, request, **kwargs):
        self.request.upload_handlers.insert(0, S3FileUploadHandler(request))

        good_id = str(kwargs["good_pk"])
        draft_id = str(kwargs["pk"])
        data, error = add_document_data(request)

        if error:
            return error_page(request, error)

        if "errors" in post_good_documents(request, good_id, data):
            return error_page(request, strings.goods.AttachDocumentPage.UPLOAD_FAILURE_ERROR)

        return redirect(
            reverse_lazy("applications:add_good_to_application", kwargs={"pk": draft_id, "good_pk": good_id})
        )


class DraftOpenGoodsTypeList(TemplateView):
    def get(self, request, **kwargs):
        application_id = str(kwargs["pk"])
        application = get_application(request, application_id)
        goods = get_application_goods_types(request, application_id)

        context = {
            "goods": goods,
            "application": application,
        }
        return render(request, "applications/goodstype/index.html", context)


class AddGoodToApplication(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = kwargs["pk"]
        application = get_application(self.request, self.object_pk)
        good, _ = get_good(request, kwargs["good_pk"])
        self.form = good_on_application_form(request, good, application["case_type"]["sub_type"], self.object_pk)
        self.action = post_good_on_application
        self.success_url = reverse_lazy("applications:goods", kwargs={"pk": self.object_pk})


class RemovePreexistingGood(TemplateView):
    def get(self, request, **kwargs):
        application_id = str(kwargs["pk"])
        good_on_application_id = str(kwargs["good_on_application_pk"])

        status_code = delete_application_preexisting_good(request, good_on_application_id)

        if status_code != 200:
            return error_page(request, "Unexpected error removing product")

        return redirect(reverse_lazy("applications:goods", kwargs={"pk": application_id}))

applications/views/goods_types.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from applications.forms.goods_types import goods_type_form
from applications.helpers.get_application_edit_type import get_application_edit_type, ApplicationEditTypes
from applications.services import (
    delete_goods_type,
    post_goods_type,
    put_goods_type_countries,
    get_application_goods_types,
    get_application_countries,
    get_application,
)
from lite_forms.generators import error_page
from lite_forms.views import SingleFormView


class GoodsTypeList(TemplateView):
    def get(self, request, **kwargs):
        application_id = str(kwargs["pk"])
        application = get_application(request, application_id)
        goods = get_application_goods_types(request, application_id)

        if not application["goods_types"]:
            return redirect(reverse_lazy("applications:add_goods_type", kwargs={"pk": application_id}))

        context = {
            "goods": goods,
            "application": application,
        }
        return render(request, "applications/goods-types/index.html", context)


class GoodsTypeAdd(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = kwargs["pk"]
        application = get_application(request, self.object_pk)
        self.form = goods_type_form(application.sub_type)
        self.action = post_goods_type
        self.success_url = reverse_lazy("applications:goods_types", kwargs={"pk": self.object_pk})


class GoodsTypeRemove(TemplateView):
    def get(self, request, **kwargs):
        application_id = str(kwargs["pk"])
        good_type_id = str(kwargs["goods_type_pk"])

        status_code = delete_goods_type(request, application_id, good_type_id)

        if status_code != 200:
            return error_page(request, "Unexpected error removing product description")

        return redirect(reverse_lazy("applications:goods_types", kwargs={"pk": application_id}))


class GoodsTypeCountries(TemplateView):
    """
    View to control which goods are going to which countries (goods/countries matrix)
    """

    application_id = None
    application = None
    goods = None
    countries = None

    def dispatch(self, request, *args, **kwargs):
        self.application_id = str(kwargs["pk"])
        self.application = get_application(request, self.application_id)
        self.goods = get_application_goods_types(request, self.application_id)
        self.countries = get_application_countries(request, self.application_id)

        # Prevent minor edits from accessing this page
        if get_application_edit_type(self.application) == ApplicationEditTypes.MINOR_EDIT:
            raise Http404

        return super(GoodsTypeCountries, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = {
            "countries": self.countries,
            "goods": self.goods,
            "draft_id": self.application_id,
            "select": request.GET.get("all", None),
        }
        return render(request, "applications/goods-types/countries.html", context)

    def post(self, request, **kwargs):
        data = request.POST.copy()
        data.pop("csrfmiddlewaretoken")

        post_data = {}

        for good_country in data:
            split_data = good_country.split(".")
            if str(split_data[0]) not in str(post_data):
                post_data[split_data[0]] = []
            post_data[split_data[0]].append(split_data[1])

        for good in self.goods:
            if good["id"] not in str(data):
                post_data[good["id"]] = []

        data, _ = put_goods_type_countries(request, self.application_id, post_data)

        if "errors" in data:
            # Merge post data and existing goods
            for good in self.goods:
                good["countries"] = [{"id": x} for x in post_data[good["id"]]]

            context = {
                "countries": self.countries,
                "goods": self.goods,
                "draft_id": self.application_id,
                "select": request.GET.get("all", None),
                "errors": data["errors"],
            }
            return render(request, "applications/goods-types/countries.html", context)

        return redirect(reverse_lazy("applications:task_list", kwargs={"pk": self.application_id}))

templates/goods/delete-document.html
{% extends 'layouts/base.html' %}

{% load svg %}

{% block back_link %}
	<a href="{% url 'goods:good_detail' good.id "case-notes" %}" id="back-link" class="govuk-back-link">{% lcs "goods.DeleteGoodDocumentPage.BACK" %}</a>
{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">{% block title %}{{ title }}{% endblock %}</h1>
			<dl class="govuk-summary-list" id="good-details">
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs "goods.DeleteGoodDocumentPage.DOCUMENT_NAME" %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ document.name }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs "goods.DeleteGoodDocumentPage.DOCUMENT_CREATED_AT" %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ document.created_at|str_date }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs "goods.DeleteGoodDocumentPage.DOCUMENT_CREATED_BY" %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ document.user.first_name }} {{ document.user.last_name }}
					</dd>
				</div>
				<div class="govuk-summary-list__row">
					<dt class="govuk-summary-list__key">
						{% lcs "goods.DeleteGoodDocumentPage.DOCUMENT_DESCRIPTION" %}
					</dt>
					<dd class="govuk-summary-list__value">
						{{ document.description|default_na|slice:"0:40" }} {% if document.description|length > 40 %}...{% endif %}
					</dd>
				</div>
			</dl>
		</div>
	</div>

	<div class="buttons-row">
	<form method="post" action="{% url 'goods:delete_document' good.id document.id %}">
		{% csrf_token %}
		<button type="submit" class="govuk-button govuk-button--warning govuk-!-margin-right-2">{% lcs "goods.DeleteGoodDocumentPage.BUTTON" %}</button>
	</form>
</div>
{% endblock %}

templates/goods/goods.html
{% extends 'layouts/base.html' %}

{% load svg static %}

{% block back_link %}
	{% include 'includes/breadcrumbs.html' with title='goods.GoodsList.TITLE' %}
{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}
					{% lcs 'goods.GoodsList.TITLE' %}
				{% endblock %}
			</h1>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'goods:add' %}" id="button-add-a-good" class="govuk-button" draggable="false" role="button">
				{% lcs 'goods.GoodsList.CREATE_GOOD' %}
			</a>
		</div>
	</div>

	{% if goods.count or filtered %}
		<div class="lite-js-only">
			<a href="#" id="show-filters-link" class="govuk-link govuk-link--no-visited-state lite-filter-toggle-link">
				{% svg 'plus' %}
				{% lcs 'goods.GoodsList.Filter.SHOW' %}
			</a>
			<a href="#" id="hide-filters-link" class="govuk-link govuk-link--no-visited-state lite-filter-toggle-link">
				{% svg 'minus' %}
				{% lcs 'goods.GoodsList.Filter.HIDE' %}
			</a>
		</div>
		<form id="filters" action="{% url 'goods:goods'%}" method="get">
			<div class="govuk-grid-row lite-filter-bar">
				<div class="govuk-grid-column-one-third">
					<label class="govuk-label" for="description">
						{% lcs 'goods.GoodsList.Filter.DESCRIPTION' %}
					</label>
					<input class="govuk-input" id="description" name="description" type="text" autocomplete="off" autocorrect="off"  value="{{ description }}">
				</div>
				<div class="govuk-grid-column-one-third">
					<label class="govuk-label" for="control_rating">
						{% lcs 'goods.GoodsList.Filter.CONTROL_LIST_ENTRY' %}
					</label>
					<input class="govuk-input" id="control_rating" name="control_rating" type="text" autocomplete="off" autocorrect="off"  value="{{ control_code }}">
				</div>
				<div class="govuk-grid-column-one-third">
					<label class="govuk-label" for="part_number">
						{% lcs 'goods.GoodsList.Filter.PART_NUMBER' %}
					</label>
					<input class="govuk-input" id="part_number" name="part_number" type="text" autocomplete="off" autocorrect="off"  value="{{ part_number }}">
				</div>
				<div class="govuk-grid-column-one-third govuk-!-margin-top-6">
					<button type="submit" form="filters" class="govuk-button govuk-!-margin-0" id="button-apply-filters">
						{% lcs 'goods.GoodsList.Filter.APPLY' %}
					</button>
					<a href="{% url 'goods:goods' %}" class="govuk-button govuk-!-margin-bottom-0 govuk-!-margin-left-3 govuk-button--secondary govuk-button--secondary-white" id="button-clear-filters">
						{% lcs 'goods.GoodsList.Filter.CLEAR' %}
					</a>
				</div>
			</div>
		</form>
	{% endif %}

	{% if not filtered and not goods.count %}
		{% include "includes/notice.html" with text='goods.GoodsList.Count.ORGANISATION_ZERO' %}
	{% elif not goods.count %}
		{% include "includes/notice.html" with text='goods.GoodsList.Count.FILTERED_ZERO' %}
	{% else %}
		<p class="govuk-caption-m govuk-!-margin-top-1">
			{% if not filtered %}
				{% include 'includes/pluralise.html' with count=goods.count base_constant='goods.GoodsList.Count.ORGANISATION' %}
			{% else %}
				{% include 'includes/pluralise.html' with count=goods.count base_constant='goods.GoodsList.Count.FILTERED' %}
			{% endif %}
		</p>
	{% endif %}

	{% if goods.count %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">{% lcs 'goods.GoodsList.Table.DESCRIPTION' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'goods.GoodsList.Table.CONTROL_LIST_ENTRY' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'goods.GoodsList.Table.PART_NUMBER' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'goods.GoodsList.Table.STATUS' %}</th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for good in goods.results %}
					<tr class="govuk-table__row">
						<td class="govuk-table__cell">
							<a class="govuk-link govuk-link--no-visited-state app-icon-label" href="{% url "goods:good" good.id %}" id="good-description">
								<p>{{ good.description|highlight_text:description }}</p>
								{% if good.status.key == 'verified' %}<span class="app-verified__symbol">{% svg "verified" %}</span>{% endif %}
								{% if good.query.exporter_user_notification_count.total %}
									<span class="lite-notification-bubble">{{ good.query.exporter_user_notification_count.total }} <span class="govuk-visually-hidden"> {% lcs "goods.GoodsPage.NOTIFICATIONS" %}</span></span>
								{% endif %}
							</a>
						</td>
						<td class="govuk-table__cell" id="good-control_code">{{ good.control_code|highlight_text:control_code|default_na }}</td>
						<td class="govuk-table__cell" id="good-part-number">{{ good.part_number|highlight_text:part_number|default_na }}</td>
						<td class="govuk-table__cell">{{ good.status.value }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "includes/pagination.html" with data=goods %}
	{% endif %}
{% endblock %}

{% block javascript %}
	<script src="{% static 'javascripts/filter-bar.js' %}"></script>
{% endblock %}