applications/urls.py
from django.urls import path

from applications.views.parties import consignees, end_users, third_parties, ultimate_end_users
from applications.views import (
    goods,
    documents,
    locations,
    additional_documents,
    common,
    edit,
    told_by_an_official,
    optional_note,
    goods_types,
    f680_details,
    clearance,
    questions,
    end_use_details,
)

app_name = "applications"
urlpatterns = [
    # Common
    path("", common.ApplicationsList.as_view(), name="applications"),
    path("<uuid:pk>/delete/", common.DeleteApplication.as_view(), name="delete"),
    path("<uuid:pk>/task-list/", common.ApplicationTaskList.as_view(), name="task_list"),
    path("<uuid:pk>/submit-success/", common.ApplicationSubmitSuccessPage.as_view(), name="success_page"),
    path("<uuid:pk>/edit-type/", common.ApplicationEditType.as_view(), name="edit_type"),
    path("<uuid:pk>/check-your-answers/", common.CheckYourAnswers.as_view(), name="check_your_answers"),
    path("<uuid:pk>/submit/", common.Submit.as_view(), name="submit"),
    path("<uuid:pk>/copy/", common.ApplicationCopy.as_view(), name="copy"),
    path("<uuid:pk>/ecju-queries/<uuid:query_pk>/", common.RespondToQuery.as_view(), name="respond_to_query"),
    # Standard and Open Licence
    path("<uuid:pk>/edit/reference-name/", edit.EditReferenceName.as_view(), name="edit_reference_name",),
    path("<uuid:pk>/edit/goods-categories/", edit.EditGoodsCategories.as_view(), name="edit_goods_categories",),
    path(
        "<uuid:pk>/edit/told-by-an-official/",
        told_by_an_official.ApplicationEditToldByAnOfficial.as_view(),
        name="edit_told_by_an_official",
    ),
    # HMRC Query
    path("<uuid:pk>/optional-note/", optional_note.ApplicationOptionalNote.as_view(), name="optional_note"),
    # Goods
    path("<uuid:pk>/goods/", goods.DraftGoodsList.as_view(), name="goods"),
    path("<uuid:pk>/goods/add-new/", goods.AddGood.as_view(), name="new_good"),
    path(
        "<uuid:pk>/goods/add-new/<uuid:good_pk>/add-document/",
        goods.CheckDocumentGrading.as_view(),
        name="add_document",
    ),
    path("<uuid:pk>/goods/add-new/<uuid:good_pk>/attach/", goods.AttachDocument.as_view(), name="attach_documents"),
    path("<uuid:pk>/goods/add-preexisting/", goods.GoodsList.as_view(), name="preexisting_good"),
    path("<uuid:pk>/goods/<uuid:good_pk>/add/", goods.AddGoodToApplication.as_view(), name="add_good_to_application",),
    path(
        "<uuid:pk>/good-on-application/<uuid:good_on_application_pk>/remove/",
        goods.RemovePreexistingGood.as_view(),
        name="remove_preexisting_good",
    ),
    # F680 details
    path("<uuid:pk>/f680-details/", f680_details.F680Details.as_view(), name="f680_details"),
    path("<uuid:pk>/questions/", questions.AdditionalInformationFormView.as_view(), name="questions"),
    # Goods Types
    path("<uuid:pk>/goods-types/", goods_types.GoodsTypeList.as_view(), name="goods_types"),
    path("<uuid:pk>/goods-types/countries/", goods_types.GoodsTypeCountries.as_view(), name="goods_countries"),
    path("<uuid:pk>/goods-types/add/", goods_types.GoodsTypeAdd.as_view(), name="add_goods_type"),
    path(
        "<uuid:pk>/goods-types/remove/<uuid:goods_type_pk>/",
        goods_types.GoodsTypeRemove.as_view(),
        name="remove_goods_type",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/attach",
        documents.AttachDocuments.as_view(),
        name="goods_type_attach_document",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="goods_type_download_document",
    ),
    path(
        "<uuid:pk>/goods-types/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="goods_type_delete_document",
    ),
    # Goods locations
    path("<uuid:pk>/goods-locations/", locations.GoodsLocation.as_view(), name="location"),
    path("<uuid:pk>/goods-locations/edit/", locations.EditGoodsLocation.as_view(), name="edit_location"),
    path("<uuid:pk>/goods-locations/existing-sites/", locations.ExistingSites.as_view(), name="existing_sites"),
    path(
        "<uuid:pk>/goods-locations/external-locations/select/",
        locations.SelectAddExternalLocation.as_view(),
        name="select_add_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/add/",
        locations.AddExternalLocation.as_view(),
        name="add_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/<uuid:ext_loc_pk>/",
        locations.RemoveExternalLocation.as_view(),
        name="remove_external_location",
    ),
    path(
        "<uuid:pk>/goods-locations/external-locations/preexisting/",
        locations.AddExistingExternalLocation.as_view(),
        name="add_preexisting_external_location",
    ),
    path("<uuid:pk>/goods-locations/countries/", locations.Countries.as_view(), name="countries"),
    # End User
    path("<uuid:pk>/end-user/", end_users.EndUser.as_view(), name="end_user"),
    path("<uuid:pk>/end-user/add/", end_users.AddEndUser.as_view(), name="add_end_user"),
    path("<uuid:pk>/end-user/set/", end_users.SetEndUser.as_view(), name="set_end_user"),
    path("<uuid:pk>/end-user/copy/", end_users.CopyEndUsers.as_view(), name="end_users_copy"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/", end_users.EndUser.as_view(), name="end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/edit/", end_users.EditEndUser.as_view(), name="edit_end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/copy/", end_users.CopyEndUser.as_view(), name="copy_end_user"),
    path("<uuid:pk>/end-user/<uuid:obj_pk>/remove/", end_users.RemoveEndUser.as_view(), name="remove_end_user"),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/attach/",
        documents.AttachDocuments.as_view(),
        name="end_user_attach_document",
    ),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="end_user_download_document",
    ),
    path(
        "<uuid:pk>/end-user/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="end_user_delete_document",
    ),
    # Consignee
    path("<uuid:pk>/consignee/", consignees.Consignee.as_view(), name="consignee"),
    path("<uuid:pk>/consignee/add/", consignees.AddConsignee.as_view(), name="add_consignee"),
    path("<uuid:pk>/consignee/set/", consignees.SetConsignee.as_view(), name="set_consignee"),
    path("<uuid:pk>/consignee/copy/", consignees.CopyConsignees.as_view(), name="consignees_copy"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/", consignees.Consignee.as_view(), name="consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/edit/", consignees.EditConsignee.as_view(), name="edit_consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/copy/", consignees.CopyConsignee.as_view(), name="copy_consignee"),
    path("<uuid:pk>/consignee/<uuid:obj_pk>/remove/", consignees.RemoveConsignee.as_view(), name="remove_consignee"),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/attach/",
        documents.AttachDocuments.as_view(),
        name="consignee_attach_document",
    ),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="consignee_download_document",
    ),
    path(
        "<uuid:pk>/consignee/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="consignee_delete_document",
    ),
    # End use details
    path("<uuid:pk>/end-use-details/", end_use_details.EndUseDetails.as_view(), name="end_use_details"),
    # Ultimate end users
    path("<uuid:pk>/ultimate-end-users/", ultimate_end_users.UltimateEndUsers.as_view(), name="ultimate_end_users"),
    path(
        "<uuid:pk>/ultimate-end-users/add/",
        ultimate_end_users.AddUltimateEndUser.as_view(),
        name="add_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/set/",
        ultimate_end_users.SetUltimateEndUser.as_view(),
        name="set_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/copy/",
        ultimate_end_users.CopyUltimateEndUsers.as_view(),
        name="ultimate_end_users_copy",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/copy/",
        ultimate_end_users.CopyUltimateEndUser.as_view(),
        name="copy_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/remove/",
        ultimate_end_users.RemoveUltimateEndUser.as_view(),
        name="remove_ultimate_end_user",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/",
        ultimate_end_users.UltimateEndUsers.as_view(),
        name="ultimate_end_users",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/attach",
        documents.AttachDocuments.as_view(),
        name="ultimate_end_user_attach_document",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/download",
        documents.DownloadDocument.as_view(),
        name="ultimate_end_user_download_document",
    ),
    path(
        "<uuid:pk>/ultimate-end-users/<uuid:obj_pk>/document/delete",
        documents.DeleteDocument.as_view(),
        name="ultimate_end_user_delete_document",
    ),
    # Third parties
    path("<uuid:pk>/third-parties/", third_parties.ThirdParties.as_view(), name="third_parties"),
    path("<uuid:pk>/third-parties/add/", third_parties.AddThirdParty.as_view(), name="add_third_party"),
    path("<uuid:pk>/third-parties/set/", third_parties.SetThirdParty.as_view(), name="set_third_party"),
    path("<uuid:pk>/third-parties/copy/", third_parties.CopyThirdParties.as_view(), name="third_parties_copy"),
    path("<uuid:pk>/third-parties/<uuid:obj_pk>/", third_parties.ThirdParties.as_view(), name="third_parties"),
    path(

conf/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("applications/", include("applications.urls")),
    path("apply-for-a-licence/", include("apply_for_a_licence.urls")),
    path("auth/", include("auth.urls")),
    path("end-users/", include("end_users.urls")),
    path("goods/", include("goods.urls")),
    path("licences/", include("licences.urls")),
    path("organisation/", include("organisation.urls")),
    path("", include("hmrc.urls")),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"
urlpatterns = [
    path("", views.Goods.as_view(), name="goods"),
    path("add/", views.AddGood.as_view(), name="add"),
    path("<uuid:pk>/edit/", views.EditGood.as_view(), name="edit"),
    path("<uuid:pk>/delete/", views.DeleteGood.as_view(), name="delete"),
    path("<uuid:pk>/add-document/", views.CheckDocumentGrading.as_view(), name="add_document"),
    path("<uuid:pk>/documents/<uuid:file_pk>/", views.Document.as_view(), name="document"),
    path("<uuid:pk>/documents/<uuid:file_pk>/delete/", views.DeleteDocument.as_view(), name="delete_document"),
    path("<uuid:pk>/attach/", views.AttachDocuments.as_view(), name="attach_documents"),
    path("<uuid:pk>/raise-good-query/", views.RaiseGoodsQuery.as_view(), name="raise_goods_query"),
    path("<uuid:pk>", views.GoodsDetailEmpty.as_view(), name="good"),
    path("<uuid:pk>/<str:type>/", views.GoodsDetail.as_view(), name="good_detail"),
    path("<uuid:pk>/ecju-queries/<uuid:query_pk>/", views.RespondToQuery.as_view(), name="respond_to_query"),
]

hub/urls.py
from django.urls import path

from . import views

app_name = 'hub'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
]

applications/forms/application_actions.py
from django.urls import reverse_lazy

from applications.helpers.summaries import application_summary
from lite_content.lite_exporter_frontend import strings
from lite_forms.generators import confirm_form


def withdraw_application_confirmation(application, pk):
    return confirm_form(
        title=strings.applications.ApplicationSummaryPage.Withdraw.TITLE,
        confirmation_name="choice",
        summary=application_summary(application),
        back_link_text=strings.applications.ApplicationSummaryPage.Withdraw.BACK_TEXT,
        yes_label=strings.applications.ApplicationSummaryPage.Withdraw.YES_LABEL,
        no_label=strings.applications.ApplicationSummaryPage.Withdraw.NO_LABEL,
        submit_button_text=strings.applications.ApplicationSummaryPage.Withdraw.SUBMIT_BUTTON,
        back_url=reverse_lazy("applications:application", kwargs={"pk": pk}),
        side_by_side=True,
    )


def surrender_application_confirmation(application, pk):
    return confirm_form(
        title=strings.applications.ApplicationSummaryPage.Surrender.TITLE,
        confirmation_name="choice",
        summary=application_summary(application),
        back_link_text=strings.applications.ApplicationSummaryPage.Surrender.BACK_TEXT,
        yes_label=strings.applications.ApplicationSummaryPage.Surrender.YES_LABEL,
        no_label=strings.applications.ApplicationSummaryPage.Surrender.NO_LABEL,
        submit_button_text=strings.applications.ApplicationSummaryPage.Surrender.SUBMIT_BUTTON,
        back_url=reverse_lazy("applications:application", kwargs={"pk": pk}),
        side_by_side=True,
    )

applications/forms/countries.py
from applications.components import back_to_task_list
from core.services import get_countries
from lite_content.lite_exporter_frontend import strings
from lite_forms.components import Form, Filter, Checkboxes


def countries_form(application_id):
    return Form(
        title=strings.applications.DestinationForm.TITLE,
        description=strings.applications.DestinationForm.DESCRIPTION,
        questions=[
            Filter(),
            Checkboxes(
                name="countries[]",
                options=get_countries(None, True),
                classes=["govuk-checkboxes--small"],
                show_select_links=True,
            ),
        ],
        javascript_imports=["/assets/javascripts/filter-checkbox-list.js"],
        default_button_name=strings.SAVE,
        back_link=back_to_task_list(application_id),
    )

applications/forms/documents.py
from django.urls import reverse_lazy

from lite_content.lite_exporter_frontend.applications import DeletePartyDocumentForm
from lite_forms.components import Form, FileUpload, TextArea, BackLink, Label
from lite_forms.generators import confirm_form


def attach_document_form(application_id, strings, back_link):
    return Form(
        strings.TITLE,
        strings.DESCRIPTION,
        [FileUpload(), TextArea(title=strings.DESCRIPTION_FIELD_TITLE, optional=True, name="description")],
        back_link=BackLink(strings.BACK, reverse_lazy(back_link, kwargs={"pk": application_id})),
        footer_label=Label(
            'Or <a id="return_to_application" href="'
            + str(reverse_lazy("applications:task_list", kwargs={"pk": application_id}))
            + '" class="govuk-link govuk-link--no-visited-state">'
            + strings.SAVE_AND_RETURN_LATER
            + "</a> "
            + strings.ATTACH_LATER
        ),
    )


def delete_document_confirmation_form(overview_url, strings):
    return confirm_form(
        title=DeletePartyDocumentForm.TITLE,
        confirmation_name="delete_document_confirmation",
        back_link_text=strings.BACK,
        back_url=overview_url,
    )

applications/views/additional_documents.py
from django.shortcuts import render
from django.views.generic import TemplateView

from applications.services import get_additional_documents, get_application


class AdditionalDocuments(TemplateView):
    def get(self, request, **kwargs):
        application_id = str(kwargs["pk"])
        application = get_application(request, application_id)
        data, _ = get_additional_documents(request, application_id)

        context = {"additional_documents": data["documents"], "application": application, "editable": data["editable"]}

        return render(request, "applications/additional-documents/additional-documents.html", context)

applications/views/clearance.py
from django.urls import reverse_lazy

from applications.components import back_to_task_list
from applications.services import put_application, get_application
from core.services import get_pv_gradings
from lite_content.lite_exporter_frontend.applications import ClearanceLevel
from lite_forms.components import Form, RadioButtons
from lite_forms.views import SingleFormView


def clearance_level_form(application_id, options):
    return Form(
        title=ClearanceLevel.TITLE,
        description=ClearanceLevel.DESCRIPTION,
        questions=[RadioButtons(name="clearance_level", options=options)],
        back_link=back_to_task_list(application_id),
    )


class SetClearanceLevel(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = kwargs["pk"]
        pv_grading_options = get_pv_gradings(request, convert_to_options=True)
        self.form = clearance_level_form(application_id=kwargs["pk"], options=pv_grading_options)
        self.action = put_application
        self.success_url = reverse_lazy("applications:task_list", kwargs={"pk": self.object_pk})
        application = get_application(request, self.object_pk)
        self.data = {"clearance_level": application["clearance_level"]}

templates/applications/goods/index.html
{% extends 'layouts/base.html' %}

{% load svg humanize %}

{% block back_link %}
	<a href="{% url 'applications:task_list' application.id %}" id="back-link" class="govuk-back-link">Back to application overview</a>
{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}{% lcs 'goods.ViewGoodOnApplicationPage.TITLE' %}{% endblock %}
			</h1>
		</div>
		{% if application.status.key in 'applicant_editing,draft' %}
			<div class="lite-app-bar__controls">
				<a id="button-add-new-good" href="{% url 'applications:new_good' application.id %}" role='button' draggable='false' class='govuk-button'>{% lcs 'goods.ViewGoodOnApplicationPage.ADD_NEW_BUTTON' %}</a>
				<a id="button-add-preexisting-good" href="{% url 'applications:preexisting_good' application.id %}" role='button' draggable='false' class='govuk-button'>{% lcs 'Goods.AddFromOrganisation.BUTTON' %}</a>
			</div>
		{% endif %}
	</div>

	{% if goods %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th scope="col" class="govuk-table__header">#</th>
					<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.DESCRIPTION' %}</th>
					<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.CONTROL_LIST_ENTRY' %}</th>
					<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.PART_NUMBER' %}</th>
					{% if exhibition %}
						<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.PRODUCT_TYPE' %}</th>
					{% else %}
						<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.QUANTITY' %}</th>
						<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.VALUE' %}</th>
						<th scope="col" class="govuk-table__header">{% lcs 'goods.GoodsList.Table.INCORPORATED' %}</th>
					{% endif %}
					<th scope="col" class="govuk-table__header"></th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for good_on_application in goods %}
					<tr class="govuk-table__row">
						<td class="govuk-table__cell govuk-table__cell--line-number">
							{{ forloop.counter }}.
						</td>
						<td class="govuk-table__cell">
							{{ good_on_application.good.description }}
							{% if good_on_application.good.status.key == 'verified' %}<span class="app-verified__symbol">{% svg 'verified' %}</span><span class="govuk-visually-hidden"> (Verified product)</span>{% endif %}
						</td>
						<td class="govuk-table__cell">
							{{ good_on_application.good.control_code|default_na }}
						</td>
						<td class="govuk-table__cell">
							{{ good_on_application.good.part_number|default_na }}
						</td>
						{% if exhibition %}
							<td class="govuk-table__cell">
								{% if good_on_application.other_item_type %}
									{{ good_on_application.other_item_type|title }}
								{% else %}
									{{ good_on_application.item_type|title }}
								{% endif %}
							</td>
						{% else %}
							<td class="govuk-table__cell">
								{{ good_on_application.quantity|intcomma }} {{ good_on_application.unit.value|units_pluralise:good_on_application.quantity }}
							</td>
							<td class="govuk-table__cell">
								£{{ good_on_application.value|intcomma }}
							</td>
							<td class="govuk-table__cell">
								{{ good_on_application.is_good_incorporated|friendly_boolean }}
							</td>
						{% endif %}
						<td class="govuk-table__cell govuk-table__cell--numeric">
							<a class="govuk-link" href="{% url 'applications:remove_preexisting_good' application.id good_on_application.id %}">
								Remove
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% if goods_value %}
			<p class="govuk-body govuk-!-font-weight-bold">Total value<span class="govuk-visually-hidden"> of products</span>: <span id="span-goods-total-value">£{{ goods_value|intcomma }}</span></p>
		{% endif %}
	{% else %}
		{% include "includes/notice.html" with text='goods.ViewGoodOnApplicationPage.NO_CONTENT' help='goods.ViewGoodOnApplicationPage.NO_CONTENT_DESCRIPTION' %}
	{% endif %}
{% endblock %}

templates/applications/goods/preexisting.html
{% extends 'layouts/base.html' %}

{% load static svg %}

{% block back_link %}
	<a href="{% url 'applications:goods' draft_id %}" id="back-link" class="govuk-back-link">Back to products</a>
{% endblock%}

{% block body %}
	<h1 class="govuk-heading-l">{% block title %}{% lcs 'goods.AddPreexistingGoodToApplicationForm.TITLE' %}{% endblock %}</h1>

	{% if data or description or part_number or control_code %}
		<div class="lite-js-only">
			<a href="#" id="show-filters-link" class="govuk-link govuk-link--no-visited-state lite-filter-toggle-link">
				{% svg 'plus' %}
				Show filters
			</a>
			<a href="#" id="hide-filters-link" class="govuk-link govuk-link--no-visited-state lite-filter-toggle-link">
				{% svg 'minus' %}
				Hide filters
			</a>
		</div>

		<div id="filters" class="govuk-grid-row lite-filter-bar">
			<form method="get">
				<div class="govuk-grid-column-one-quarter">
					<label class="govuk-label" for="description">
						Description
					</label>
					<input class="govuk-input" id="description" name="description" type="text" autocomplete="off" autocorrect="off"  value="{{ description }}">
				</div>
				<div class="govuk-grid-column-one-quarter">
					<label class="govuk-label" for="part_number">
						Part number
					</label>
					<input class="govuk-input" id="part_number" name="part_number" type="text" autocomplete="off" autocorrect="off"  value="{{ part_number }}">
				</div>
				<div class="govuk-grid-column-one-quarter">
					<label class="govuk-label" for="control_rating">
						Control list classification
					</label>
					<input class="govuk-input" id="control_rating" name="control_rating" type="text" autocomplete="off" autocorrect="off"  value="{{ control_code }}">
				</div>
				<div class="govuk-grid-column-one-quarter">
					<label class="govuk-label"></label>
					<button type="submit" class="govuk-button" id="button-apply-filters">Apply filters</button>
				</div>
			</form>
		</div>

		{% if data %}
			<table class="govuk-table">
				<thead class="govuk-table__head">
					<tr class="govuk-table__row">
						<th scope="col" class="govuk-table__header">Description</th>
						<th scope="col" class="govuk-table__header">Part number</th>
						<th scope="col" class="govuk-table__header">CLC</th>
						<th scope="col" class="govuk-table__header"></th>
					</tr>
				</thead>
				<tbody class="govuk-table__body">
					{% for good in data.results %}
						<tr class="govuk-table__row">
							<td class="govuk-table__cell" id="good-description">
								{{ good.description|highlight_text:description }}
								{% if good.status.key == 'verified' %}<span class="app-verified__symbol">{% svg 'verified' %}</span><span class="govuk-visually-hidden"> (Verified product)</span>{% endif %}
							</td>
							<td class="govuk-table__cell" id="good-part-number">
								{{ good.part_number|highlight_text:part_number|default_na }}
							</td>
							<td class="govuk-table__cell" id="good-control_code">
								{{ good.control_code|highlight_text:control_code|default_na }}
							</td>
							<td class="govuk-table__cell lite-!-text-align-right">
								<a href="{% url 'applications:add_good_to_application' draft_id good.id %}" id="add-to-application" class="govuk-link govuk-link--no-visited-state" draggable="false">
									Add <span class="govuk-visually-hidden">{{ good.description }}</span> to application
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include "includes/pagination.html" with data=data %}
		{% else %}
			<div class="lite-information-text">
				<span class="lite-information-text__icon" aria-hidden="true">!</span>
				<p class="lite-information-text__text">
					<span class="govuk-visually-hidden">Information</span>
					There are no products on your product list.
				</p>
			</div>
		{% endif %}
	{% else %}
		<div class="lite-information-text">
			<span class="lite-information-text__icon" aria-hidden="true">!</span>
			<p class="lite-information-text__text">
				<span class="govuk-visually-hidden">Information</span>
				There are no products on your product list.
			</p>
		</div>
	{% endif %}
{% endblock %}

{% block javascript %}
	<script src="{% static 'javascripts/filter-bar.js' %}"></script>
{% endblock %}